# Order is important for dependencies
models = [
  AdminUser,
  Category,
  Product,
  Service,
  Banner,
  About,
  Contact,
  Tentang
]

# Attempt to include Address if it exists and is an AR model
begin
  models << Address if defined?(Address) && Address < ApplicationRecord
rescue NameError
  # Address might not be defined
end

puts "# Generated by seed_generator.rb at #{Time.now}"
puts

models.each do |model|
  next unless model.table_exists?

  puts "# #{model.name}"
  puts "#{model.name}.destroy_all"

  model.order(:id).each do |record|
    attrs = record.attributes.except('created_at', 'updated_at')
    args = attrs.map do |key, value|
      val_str = if value.nil?
                  'nil'
                elsif value.is_a?(String)
                  value.inspect
                elsif value.is_a?(Time) || value.is_a?(Date) || value.is_a?(ActiveSupport::TimeWithZone)
                  "'#{value}'"
                else
                  value.inspect
                end
      "#{key}: #{val_str}"
    end.join(', ')

    puts "#{model.name}.create!(#{args})"
  end
  puts
rescue StandardError => e
  puts "# Error generating seeds for #{model.name}: #{e.message}"
end
